### ISSUE TITLE
Bug in initialization of `starry.Secondary()` in `Target.add_transit()`

### ISSUE THREAD

**Issue by barentsen** [nksaunders/scope#6]
I have a concern about this line in `Target.add_transit():
`https://github.com/nksaunders/scope/blob/a7d1c29ab8cec5dfa8de776ebf1c80b8769f1b04/scope/simulatetarget.py#L164

Do you mean to write `planet.inc = i`?  ... because the longitude of pericenter (w) and the inclination (i) are two separate orbital parameters.

This probably would not have caused issues in most applications because both `inc` and `w` default to 90 in both starry and scope.

**Comment by nksaunders** [comment]
Good catch @barentsen, I mixed up those parameters in my implementation. Fixed!

https://github.com/nksaunders/scope/blob/30731cd805ec66d1f859150c4b53c1c758ac68e9/scope/simulatetarget.py#L164
